<?php

/**
 * This migrates data from files in the filesystem
 */

/**
 * Implements hook_migrate_api().
 */
function migrate_hrweb_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_flush_caches().
 */
function migrate_uhs_policy_flush_caches() {
  drupal_set_message("Directory for source files is currently: " . variable_get('uhs_migration_source', '/tmp'));
  drupal_set_message("To change this use 'drush vset uhs_migration_source /path/to/my/files'");

  drupal_set_message("If the CSV source data was created on MacOS or Linux line ending auto-detection should be 'yes'.  Current state: " . variable_get('uhs_source_data_macos', "yes"));
  drupal_set_message("To change this use 'drush vset uhs_source_data_macos [no/yes]'");

  migrate_uhs_policy_register_migrations();
}


/**
 * Register all D6->D7 migrations.
 */
function migrate_uhs_policy_register_migrations() {
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 6 database), source_version (major version of Drupal), and
   * group_name (a.k.a. import job).
   */
  $common_arguments = array(
    'group_name' => 'Manuals',
    //csvcolumns is optional. can be determined from the header row.
    'csvcolumns' => array(
      array('source_id', 'The ID of the source document.'),
      array('title', 'The title of the source document.'),
      array('filename', 'The filename of the source document. (Path excluded. Just file name.)'),
      array('parent_id', "The ID of the document's immediate parent. NULL values indicate top-level items. Mimicks Drupal book structure."),
      array('source_manual', "For pages that share content, this field indicates the source of the content."),
    ),
    'options' => array(
      'header_rows' => 1,
      'embedded_newlines' => TRUE,
    ),
  );

  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.

  /*** Manuals ***/
  $common_arguments['group_name'] = "Manuals";
  $common_arguments['translations'] = array(
    'Allergy and Travel' => 'Allergy_and_Travel',
    'Care' => 'Care',
    'Clinic Assistant' => 'Clinic_Assistant',
    'Clinic Nurse Resource' => 'Clinic_Nurse_Resource',
    'CORE' => 'Core',
    'Counseling and Psychological Services' => 'Counseling_and_Psychological_Services',
    'Disability Management' => 'Disability_Management',
    'Facilities' => 'Facilities',
    'Health Net' => 'Health_Net',
    'Health Promotion' => 'Health_Promotion',
    'Health, Safety and Security' => 'Health_Safety_Security',
    'Infection Control' => 'Infection_Control',
    'Laboratory' => 'Laboratory',
    'Medical Records' => 'Medical_Records',
    'Occupational Health' => 'Occupational_Health',
    'Pharmacy' => 'Pharmacy',
    'Physical Therapby' => 'Physical_Therapy',
    'Primary & Urgent Care' => 'Primary_and_Urgent_Care',
    'Quality Improvement' => 'Quality_Improvement',
    'Radiology' => 'Radiology',
    'Risk Management' => 'Risk_Management',
    'SHIP' => 'SHIP',
    'Social Services' => 'Social_Services',
    'Specialty' => 'Specialty',
    'Sports Medicine' => 'Sports_Medicine',
    'Urgent Care RN Standing Orders' => 'Urgent_Care_RN_Standing_Orders',
    'Used in Multiple Manuals' => 'Used_in_Multiple_Manuals',
  );
  $manuals_arguments = array(
    array(
      'machine_name' => 'Used_in_Multiple_Manuals',
      'class_name' => 'UhsMigration',
      'description' => t('Import Used in Multiple Manuals (shared pages)'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Used in Multiple Manuals.csv',
    ),
    array(
      'machine_name' => 'Allergy_and_Travel',
      'class_name' => 'UhsMigration',
      'description' => t('Import Allergy manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Allergy & Travel.csv',
    ),
    array(
      'machine_name' => 'Urgent_Care_RN_Standing_Orders',
      'class_name' => 'UhsMigration',
      'description' => t('Import Urgent Care RN Standing Orders'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Urgent Care RN Standing Orders.csv',
    ),
    array(
      'machine_name' => 'Primary_and_Urgent_Care',
      'class_name' => 'UhsMigration',
      'description' => t('Import Primary & Urgent Care'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Primary & Urgent Care.csv',
    ),
    array(
      'machine_name' => 'CARE',
      'class_name' => 'UhsMigration',
      'description' => t('Import Care manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/CARE.csv',
    ),
    array(
      'machine_name' => 'Clinic_Assistant',
      'class_name' => 'UhsMigration',
      'description' => t('Import Clinic Assistant manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Clinic Assistant.csv',
    ),
    array(
      'machine_name' => 'Clinic_Nurse_Resource',
      'class_name' => 'UhsMigration',
      'description' => t('Import Clinic Nurse Resourse manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Clinic Nurse Resource.csv',
    ),
    array(
      'machine_name' => 'CORE',
      'class_name' => 'UhsMigration',
      'description' => t('Import CORE manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/CORE.csv',
    ),
    array(
      'machine_name' => 'Counseling_and_Psychological_Services',
      'class_name' => 'UhsMigration',
      'description' => t('Import Counseling and Psychological Services manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Counseling and Psychological Services.csv',
    ),
    array(
      'machine_name' => 'Disability_Management',
      'class_name' => 'UhsMigration',
      'description' => t('Import Disability Management manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Disability Management.csv',
    ),
    array(
      'machine_name' => 'Facilities',
      'class_name' => 'UhsMigration',
      'description' => t('Import Facilities manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Facilities.csv',
    ),
    array(
      'machine_name' => 'Health_Net',
      'class_name' => 'UhsMigration',
      'description' => t('Import Health Net manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Health Net.csv',
    ),
    array(
      'machine_name' => 'Health_Promotion',
      'class_name' => 'UhsMigration',
      'description' => t('Import Health Promotion manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Health Promotion.csv',
    ),
    array(
      'machine_name' => 'Health_Safety_Security',
      'class_name' => 'UhsMigration',
      'description' => t('Import Health, Safety and Security manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Health, Safety and Security.csv',
    ),
    array(
      'machine_name' => 'Infection_Control',
      'class_name' => 'UhsMigration',
      'description' => t('Import Infection Control manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Infection Control.csv',
    ),
    array(
      'machine_name' => 'Laboratory',
      'class_name' => 'UhsMigration',
      'description' => t('Import Laboratory manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Laboratory.csv',
    ),
    array(
      'machine_name' => 'Medical_Records',
      'class_name' => 'UhsMigration',
      'description' => t('Import Medical Records manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Medical Records.csv',
    ),
    array(
      'machine_name' => 'Occupational_Health',
      'class_name' => 'UhsMigration',
      'description' => t('Import Occupational Health manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Occupational Health.csv',
    ),
    array(
      'machine_name' => 'Pharmacy',
      'class_name' => 'UhsMigration',
      'description' => t('Import Pharmacy manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Pharmacy.csv',
    ),
    array(
      'machine_name' => 'Physical_Therapy',
      'class_name' => 'UhsMigration',
      'description' => t('Import Physical Therapy manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Physical Therapy.csv',
    ),
    array(
      'machine_name' => 'Quality_Improvement',
      'class_name' => 'UhsMigration',
      'description' => t('Import Quality Improvement manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Quality Improvement.csv',
    ),
    array(
      'machine_name' => 'Radiology',
      'class_name' => 'UhsMigration',
      'description' => t('Import Radiology manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Radiology.csv',
    ),
    array(
      'machine_name' => 'Risk_Management',
      'class_name' => 'UhsMigration',
      'description' => t('Import Risk Management manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Risk Management.csv',
    ),
    array(
      'machine_name' => 'SHIP',
      'class_name' => 'UhsMigration',
      'description' => t('Import SHIP manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/SHIP.csv',
    ),
    array(
      'machine_name' => 'Social_Services',
      'class_name' => 'UhsMigration',
      'description' => t('Import Social Services manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Social Services.csv',
    ),
    array(
      'machine_name' => 'Specialty',
      'class_name' => 'UhsMigration',
      'description' => t('Import Specialty manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Specialty.csv',
    ),
    array(
      'machine_name' => 'Sports_Medicine',
      'class_name' => 'UhsMigration',
      'description' => t('Import Sports Medicine manual'),
      'path' => variable_get('uhs_migration_source', '/tmp') . '/Sports Medicine.csv',
    ),
  );

  foreach ($manuals_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
      $arguments);
  }
}


/*
function migrate_uhs_policy_libraries_info() {
$libraries['querypath'] = array(
  'name' => 'QueryPath, a PHP library for working with XML and HTML',
  'vendor url' => 'https://github.com/technosophos/querypath',
  'download url' => 'https://github.com/technosophos/querypath/archive/master.zip',

  'version arguments' => array(
    'file' => 'QueryPath.php',
    'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@',
    'lines' => 4,
  ),

  'path' => 'src',
  'files' => array(
    'php' => array('QueryPath.php'),
  ),
);
  return $libraries;
}
*/
